#!/usr/bin/env python3
"""Build the primary SRLINES static pages without a runtime dependency."""
from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).parent
DOMAIN = "https://srlines.net"

NAV = {
    "Company": [("About SRLINES", "/about.html"), ("Team & Organogram", "/team.html"), ("Credentials & Partnerships", "/credentials.html"), ("Contact", "/contact.html")],
    "Services": [("Services overview", "/services/index.html"), ("Website development", "/services/website-development.html"), ("Web applications", "/services/web-application-development.html"), ("Mobile applications", "/services/mobile-application-development.html"), ("Digital advertising", "/services/digital-advertising.html"), ("NTN consultancy", "/services/ntn-consultancy.html"), ("Meta verification", "/services/meta-verification.html"), ("n8n deployment", "/services/n8n-installation.html"), ("n8n automation", "/services/n8n-workflows.html")],
    "Products": [("Products overview", "/products/index.html"), ("wCRM", "/products/wcrm.html"), ("Mobile app", "/products/wcrm-mobile.html"), ("Shopify app", "/products/wcrm-shopify.html"), ("n8n node", "/products/wcrm-n8n.html"), ("WooCommerce plugin", "/products/wcrm-woocommerce.html"), ("Bitrix24 app", "/products/wcrm-bitrix24.html")],
    "Portfolio": [("Client projects", "/portfolio/index.html"), ("SignSyncer", "/portfolio/signsyncer.html"), ("FormSyncer", "/portfolio/formsyncer.html"), ("Whatsell", "/portfolio/whatsell.html")],
    "Industries": [("Real estate", "/industries/real-estate.html"), ("Ecommerce", "/industries/ecommerce.html"), ("Internet service providers", "/industries/isp.html")],
}

services = [
 ("website-development", "Website Design & Development", "Websites that make a clear business case", "Business owners and organisations that need an accessible, credible and maintainable public presence.", ["Discovery and content architecture", "Responsive interface design", "Standards-based front-end development", "SEO foundations, analytics readiness and launch support"], "Your brand assets, approved copy, domain access and a named reviewer.", [("Will you use our existing brand?", "Yes. We audit and apply the assets and guidelines you provide."), ("Is hosting included?", "Hosting and ongoing support are scoped in the quotation rather than assumed.")]),
 ("web-application-development", "Web Application Development", "Purpose-built software for real operating work", "Teams replacing spreadsheets, connecting systems or delivering a secure browser-based service.", ["Requirements and workflow mapping", "Interface and application architecture", "API and third-party integration", "Testing, deployment documentation and handover"], "Process owners, sample data, integration documentation and access to test environments.", [("Can you integrate an existing system?", "We assess available APIs, data ownership and vendor constraints during discovery."), ("Who owns the deliverables?", "Ownership, licences and access are made explicit in the project agreement.")]),
 ("mobile-application-development", "Mobile Application Development", "Mobile experiences planned around real users", "Businesses that need a companion app, field workflow or customer-facing mobile product.", ["Product discovery and user flows", "Mobile UI design", "API-connected application development", "Testing and store-release preparation"], "Target platforms, user scenarios, brand assets, API details and store-account access where publishing is included.", [("Do you guarantee store approval?", "No. We prepare submissions and address technical feedback, while stores control approval."), ("Can a mobile app connect to our web system?", "Yes, where a suitable API and permissions are available.")]),
 ("digital-advertising", "Digital Advertising Management", "Accountable campaign operations across Meta, Google and TikTok", "Brands that need structured campaign setup, creative coordination, measurement and ongoing optimisation.", ["Account and tracking audit", "Campaign structure and audience planning", "Creative briefing and launch management", "Reporting and optimisation recommendations"], "Platform access through approved roles, offer details, creative assets, budget confirmation and compliant landing pages.", [("Is advertising spend included?", "No. Media spend and our management scope are identified separately in the quotation."), ("Can you guarantee results?", "No. Performance depends on the offer, market, budget, creative and platform delivery.")]),
 ("ntn-consultancy", "NTN Consultancy", "Practical assistance preparing for National Tax Number registration", "Individuals and businesses in Pakistan seeking help understanding and preparing an NTN application.", ["Requirements checklist", "Document-readiness review", "Application preparation guidance", "Support responding to routine process questions"], "Accurate identity, business, address and registration information plus documents required by the applicable FBR process.", [("Are you a government authority?", "No. SRLINES provides consultancy; FBR controls registration and decisions."), ("Is an NTN guaranteed?", "No. We assist with preparation and guidance but cannot guarantee acceptance or timing.")]),
 ("meta-verification", "Meta Business Portfolio Verification Consultancy", "Prepare a consistent, supportable verification submission", "Businesses that need guidance aligning their legal, web and Meta portfolio information.", ["Business-information consistency review", "Document and domain-readiness checklist", "Portfolio settings guidance", "Submission preparation and follow-up guidance"], "Authorised portfolio access, current legal documents, a business domain and accurate public contact information.", [("Can SRLINES approve verification?", "No. Meta alone controls eligibility, review and approval."), ("Do you have privileged access?", "No. We provide preparation and platform guidance without claiming privileged decision-making access.")]),
 ("n8n-installation", "n8n Installation, Configuration & Deployment", "A documented automation environment your team can operate", "Organisations that want a self-managed or appropriately hosted n8n deployment.", ["Deployment architecture review", "Installation and baseline configuration", "Credentials, webhook and backup planning", "Operational documentation and handover"], "Infrastructure access, domain and DNS control, security requirements, email configuration and an accountable technical contact.", [("Does this include workflow development?", "Baseline workflows can be scoped; complex automations are handled as a separate workstream."), ("Can you deploy anywhere?", "We first confirm that the selected provider supports the required runtime, networking and persistence.")]),
 ("n8n-workflows", "Custom n8n Workflows & Business Automation", "Connect repetitive work into observable workflows", "Teams moving data manually between sales, support, commerce and operational systems.", ["Workflow and exception mapping", "Connector and API assessment", "Workflow implementation and testing", "Monitoring guidance, documentation and handover"], "Process examples, authorised API credentials, sample records, business rules and an owner for acceptance testing.", [("Can every platform be automated?", "Only where supported access, APIs and acceptable terms allow it."), ("How do you handle failures?", "We define validation, retries, alerts and human escalation appropriate to the workflow.")]),
]

products = [
 ("wcrm", "wCRM — Meta Assets Native CRM", "The flagship SRLINES customer-conversation workspace", "Core CRM", "Shared inboxes, sales pipelines, campaigns and automation for teams working through official Meta assets.", "https://crm.srlines.net/", "Explore wCRM"),
 ("wcrm-mobile", "wCRM Mobile App", "Take the wCRM ecosystem with you", "Mobile application", "The official companion application for the wCRM ecosystem, available on Google Play.", "https://play.google.com/store/apps/details?id=net.srlines.wcrm", "Get it on Google Play"),
 ("wcrm-shopify", "wCRM Transactional Notifier — Shopify App", "Connect Shopify events with customer notifications", "Marketplace app", "The published Shopify app in the wCRM ecosystem for transactional notification workflows.", "https://apps.shopify.com/wcrm", "View on Shopify App Store"),
 ("wcrm-n8n", "wCRM n8n Node", "Build wCRM into visual automations", "Published integration", "The published n8n integration connects wCRM actions with broader business workflows.", "https://n8n.io/integrations/wcrm", "View n8n Integration"),
 ("wcrm-woocommerce", "wCRM WooCommerce Plugin", "Connect WooCommerce notification workflows", "Plugin", "A downloadable WooCommerce plugin within the wCRM integration ecosystem.", "http://srlines.net/woocommerce-whatsapp-notifications.zip", "Download Plugin"),
 ("wcrm-bitrix24", "wCRM Bitrix24 App", "Link Bitrix24 workflows with the wCRM ecosystem", "Integration app", "An integration app for organisations coordinating Bitrix24 and wCRM-related communication workflows.", "https://bitrix24.srlines.net/", "Explore Bitrix24 App"),
]

portfolio = [
 ("signsyncer", "SignSyncer", "Electronic-signing workflow implementation", "A client project developed by SRLINES. The work is presented as portfolio experience; SRLINES does not claim ownership of the client brand or business.", "web"),
 ("formsyncer", "FormSyncer", "Form-driven data workflow implementation", "A client project developed by SRLINES, involving form-based workflow and application delivery. No client identity or unsupported outcome is asserted.", "automation"),
 ("whatsell", "Whatsell", "Conversation-led commerce implementation", "A client project developed by SRLINES. It is distinct from the company-owned wCRM ecosystem and remains the client's project and brand.", "commerce"),
]

def hrefs(items):
    return ''.join(f'<a href="{u}">{escape(t)}</a>' for t,u in items)

def header(path):
    groups=''.join(f'<div class="nav-group"><button type="button" aria-expanded="false">{n}<span aria-hidden="true">⌄</span></button><div class="nav-panel">{hrefs(v)}</div></div>' for n,v in NAV.items())
    mobile=''.join(f'<details><summary>{n}</summary>{hrefs(v)}</details>' for n,v in NAV.items())
    return f'''<a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="SRLINES home"><img src="/logo.png" alt="SRLINES" width="180" height="60"></a><nav class="desktop-nav" aria-label="Primary"><a href="/">Home</a>{groups}</nav><a class="button quote" href="/contact.html">Request a Quote</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu"><span aria-hidden="true">☰</span><span>Menu</span></button></header><div class="drawer-backdrop" hidden></div><aside class="mobile-drawer" id="mobile-menu" aria-label="Mobile navigation" aria-hidden="true"><div class="drawer-head"><b>Explore SRLINES</b><button class="drawer-close" type="button" aria-label="Close menu">×</button></div><nav><a href="/">Home</a>{mobile}<a class="button" href="/contact.html">Request a Quote</a><a href="mailto:contact@srlines.net">contact@srlines.net</a></nav></aside>'''

def footer():
    return '''<footer><div><a class="brand brand-light" href="/"><img src="/logo.png" alt="SRLINES" width="180" height="60"></a><p>Ideas to Impact. Software, automation and the company-owned wCRM ecosystem, built in Pakistan for organisations here and internationally.</p></div><div><strong>Explore</strong><a href="/services/index.html">Services</a><a href="/products/index.html">Products</a><a href="/portfolio/index.html">Client projects</a><a href="/credentials.html">Credentials</a></div><div><strong>Contact</strong><a href="mailto:contact@srlines.net">contact@srlines.net</a><a href="https://wa.me/923000941558" target="_blank" rel="noopener noreferrer">WhatsApp +92 300 0941558</a><span>Sadiqabad, Punjab, Pakistan</span></div><div><strong>Legal</strong><a href="/privacy.html">Privacy</a><a href="/terms.html">Terms</a></div><small>© 2026 SRLINES SOFTWARE HOUSE (SMC-PRIVATE) LIMITED. Company-provided credential claims are described according to their stated scope.</small></footer>'''

def shell(path,title,desc,body,crumb=""):
    canonical=DOMAIN+("/" if path=="index.html" else "/"+path)
    bc=f'<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>{escape(crumb or title)}</span></nav>' if path!="index.html" else ""
    schema=json.dumps({"@context":"https://schema.org","@type":"WebPage","name":title,"url":canonical,"description":desc},separators=(',',':'))
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | SRLINES</title><meta name="description" content="{escape(desc,quote=True)}"><link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title,quote=True)} | SRLINES"><meta property="og:description" content="{escape(desc,quote=True)}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{DOMAIN}/logo.png"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/assets/redesign.css"><script type="application/ld+json">{schema}</script></head><body data-path="/{path}">{header(path)}<main id="main">{bc}{body}</main>{footer()}<script src="/assets/redesign.js" defer></script></body></html>'''

def hero(kicker,title,text,actions=''):
    return f'<section class="page-hero"><div><span class="eyebrow">{kicker}</span><h1>{title}</h1><p>{text}</p>{actions}</div><div class="hero-art" aria-hidden="true"><i></i><i></i><i></i><b>SR</b></div></section>'

def cards(items, cls="cards"):
    return f'<div class="{cls}">'+''.join(f'<article><span>{escape(a)}</span><h3>{escape(b)}</h3><p>{escape(c)}</p>{d if len(x)>3 else ""}</article>' for x in items for a,b,c,*rest in [x] for d in [rest[0] if rest else ''])+'</div>'

def faq(items):
    return '<section class="section faq"><div class="section-title"><span class="eyebrow">Questions</span><h2>Before we begin</h2></div>'+''.join(f'<details><summary>{escape(q)}</summary><p>{escape(a)}</p></details>' for q,a in items)+'</section>'

def write(path, html):
    p=ROOT/path; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(html,encoding='utf-8')

def build():
    home=hero('SRLINES SOFTWARE HOUSE (SMC-PRIVATE) LIMITED','Software that connects your business to what comes next.','We design and develop digital products, manage growth services and build practical automation—alongside our flagship wCRM Meta Assets Native CRM.','<div class="actions"><a class="button" href="/contact.html">Discuss your project</a><a class="button secondary" href="/products/wcrm.html">Explore wCRM</a></div>')
    home+='''<section class="trustline" aria-label="Company positioning"><b>Trusted. Verified. Delivering Impact.</b><span>Building a Smarter Connected Pakistan.</span></section><section class="section"><div class="section-title"><span class="eyebrow">Three connected practices</span><h2>One software house, clear areas of work.</h2></div>'''+cards([('01','Professional services','Web, mobile, advertising, consultancy and automation delivered around a documented scope.','<a href="/services/index.html">View services →</a>'),('02','The wCRM ecosystem','One company-owned CRM ecosystem: core platform, mobile app, marketplace apps, plugins and integrations.','<a href="/products/index.html">Explore products →</a>'),('03','Client projects','Selected implementation work, clearly separated from products owned by SRLINES.','<a href="/portfolio/index.html">See client projects →</a>')])+'''</section><section class="section dark"><div class="split"><div><span class="eyebrow">Flagship product</span><h2>wCRM — Meta Assets Native CRM</h2><p>Bring team conversations, pipelines, campaigns and automation into one workspace built around official Meta assets.</p><a class="button light" href="/products/wcrm.html">Explore wCRM</a></div><div class="ui-card"><b>Shared customer workspace</b><span>Inbox</span><span>Pipeline</span><span>Automation</span><span>Integrations</span></div></div></section><section class="section"><div class="section-title"><span class="eyebrow">Company-provided profile</span><h2>Credibility described precisely.</h2><p>Registrations, partnerships, published listings, certifications and technical integrations are labelled by type—not blurred into a single claim.</p></div>'''+cards([('Registered','SECP · FBR active taxpayer · PSEB · DUNS','Company-provided registration and status claims.'),('Platform ecosystem','Meta · Shopify · n8n','Partner status and published listings are stated separately on the credentials page.'),('Operating commitment','750+ businesses served · 99.9% uptime SLA','The uptime figure is a scoped service commitment, not a historical measurement.')])+'''<p class="center"><a class="text-link" href="/credentials.html">Review credentials and important qualifications →</a></p></section>'''
    write('index.html',shell('index.html','Software House, wCRM & Automation','SRLINES provides software development, professional services, the wCRM ecosystem and client project delivery from Pakistan.',home))

    about=hero('Ideas to Impact','A practical software company with connected capabilities.','SRLINES SOFTWARE HOUSE (SMC-PRIVATE) LIMITED works with business owners, agencies and operational teams in Pakistan and international markets.')+'''<section class="section split"><div><h2>What we do</h2><p>We translate business processes into websites, applications, connected workflows and measured digital operations. Our company-owned wCRM ecosystem is the flagship product line; separate client projects demonstrate delivery experience without implying ownership of client brands.</p></div><div><h2>How we work</h2><ul class="checks"><li>Clarify the problem, users and constraints</li><li>Define scope, access and acceptance criteria</li><li>Build and review in practical stages</li><li>Document launch, ownership and next steps</li></ul></div></section>'''
    write('about.html',shell('about.html','About SRLINES','Learn how SRLINES approaches software, services, owned products and client delivery.',about))

    team=hero('Team & Organogram','The people identified in the existing SRLINES website.','The prior website contained two leadership profiles but no complete departmental organogram. This page preserves those names, titles and their original order without inventing personnel or reporting lines.')+'''<section class="section organogram" aria-labelledby="org-title"><div class="section-title"><h2 id="org-title">Available organisation structure</h2><p>The connecting line records page order only; the repository did not document a formal reporting relationship.</p></div><ol><li><article><img src="/CEO-Photograph.jpg" alt="Shahid Rasool" width="320" height="400"><span>Founder &amp; CEO</span><h3>Shahid Rasool</h3><p>Leads SRLINES and its work across the Meta technology ecosystem, SaaS and software development.</p></article></li><li><article><img src="/SRLINES_BDO_BANNER.png" alt="Rubab Javed business development profile" width="560" height="560" loading="lazy"><span>Business Development Manager</span><h3>Rubab Javed</h3><p>Leads business development, connecting customers with relevant wCRM capabilities and SRLINES services.</p></article></li></ol></section>'''
    write('team.html',shell('team.html','Team & Organogram','The team profiles and hierarchy available in the existing SRLINES repository, preserved without invented roles.',team))

    cred_items=[('Registration','SECP registration','Company-provided company registration claim.'),('Tax status','FBR Active Tax Payer','Company-provided current-status claim; consult the relevant official record.'),('Registration','PSEB registration','Company-provided software exporter/industry registration claim.'),('Platform status','Meta Verified Technology Partner','Company-provided technology-provider status.'),('Partner tier','Meta Badged Partner','Company-provided current tier claim.'),('Programme','Meta Accelerator','Participation in the stated accelerator programme.'),('Partner/listing','Shopify Partner and published app','Partner status and app marketplace listing are distinct claims.'),('Partner/listing','n8n Partner and published node','Partner status and published integration are distinct claims.'),('Technology partner','Zal Ultra','Company-provided technology partnership claim.'),('Affiliate','DirectPay Affiliate Partner','Company-provided affiliate relationship claim.'),('Technical integration','Bank Alfalah payment gateway','An integration capability; not presented as a bank partnership.'),('Technical integration','1LINK / 1Bill voucher','An integration capability; not presented as a network partnership.'),('Registration','DUNS registration','Company-provided registration claim.'),('Individual learning','Coursera certification','Associated with an individual professional; not company certification.')]
    credentials=hero('Trusted. Verified. Delivering Impact.','Credentials, partnerships and integrations—with the category made clear.','These are company-provided reference claims. Where public evidence is available, links point to the relevant listing; customers should conduct their own verification.')+'<section class="section"><div class="credential-grid">'+''.join(f'<article><span>{a}</span><h2>{b}</h2><p>{c}</p></article>' for a,b,c in cred_items)+'''</div><div class="notice"><h2>Scale and service commitment</h2><p><strong>750+ businesses served</strong> is a company-provided cumulative metric. <strong>99.9% uptime SLA</strong> is a service commitment applicable only where included in the relevant agreement; it is not presented as measured historical uptime.</p><p><a href="https://apps.shopify.com/wcrm" target="_blank" rel="noopener noreferrer">Shopify app listing</a> · <a href="https://n8n.io/integrations/wcrm" target="_blank" rel="noopener noreferrer">n8n integration listing</a> · <a href="/Meta%20Tech%20Provider%20Certificate.pdf" target="_blank" rel="noopener noreferrer">Meta certificate supplied in repository</a></p></div></section>'''
    write('credentials.html',shell('credentials.html','Credentials & Partnerships','Review SRLINES registrations, partner relationships, published listings and technical integrations with clear qualifications.',credentials))

    service_cards=[]
    for slug,title,tag,audience,deliver,needs,faqs in services:
        service_cards.append(('Service',title,tag,f'<a href="/services/{slug}.html">Learn more →</a>'))
        body=hero('Professional service',title,tag,'<div class="actions"><a class="button" href="/contact.html?service='+slug+'">Request a Quote</a></div>')
        body+=f'''<section class="section"><div class="split"><div><span class="eyebrow">Business problem</span><h2>Move from an unclear requirement to an accountable delivery plan.</h2><p>{audience}</p><p>Discovery identifies the current constraint, intended users, dependencies and a useful definition of done before implementation.</p></div><div><span class="eyebrow">Scope &amp; deliverables</span><h2>What the engagement can cover</h2><ul class="checks">{''.join('<li>'+escape(x)+'</li>' for x in deliver)}</ul></div></div></section><section class="section tinted"><div class="section-title"><span class="eyebrow">Delivery process</span><h2>A transparent path from brief to handover.</h2></div>'''+cards([('01','Discover','Confirm goals, users, systems, risks and success criteria.'),('02','Define','Agree deliverables, responsibilities, review points and quotation.'),('03','Deliver','Implement in reviewable stages and test against the agreed scope.'),('04','Handover','Launch or transfer with documentation and clearly scoped support.')])+f'''</section><section class="section split"><div><h2>What you provide</h2><p>{needs}</p></div><div><h2>Relevant SRLINES experience</h2><p>Our wCRM integrations and selected <a href="/portfolio/index.html">client projects</a> demonstrate experience connecting interfaces, data and operational workflows. Relevance is confirmed during discovery rather than assumed.</p></div></section>'''+faq(faqs)+'''<section class="cta"><h2>Discuss your requirements.</h2><p>Share the business problem and available systems. We will respond with questions and a quotation path—not invented fixed pricing.</p><a class="button light" href="/contact.html">Discuss Your Project</a></section>'''
        write(f'services/{slug}.html',shell(f'services/{slug}.html',title,tag+' Scope, process, client inputs and service-specific FAQs.',body,title))
    overview=hero('Professional services','Technology and operational support, scoped around your business.','Choose a specialist service or start with the problem. Each engagement begins with requirements, dependencies and a quotation.')+'<section class="section">'+cards(service_cards)+'</section>'
    write('services/index.html',shell('services/index.html','Services','Explore SRLINES software development, advertising, consultancy, n8n deployment and automation services.',overview,'Services'))

    prod_cards=[]
    for slug,title,tag,kind,desc,url,cta in products:
        prod_cards.append((kind,title,desc,f'<a href="/products/{slug}.html">View details →</a>'))
        body=hero('wCRM ecosystem · '+kind,title,tag,f'<div class="actions"><a class="button" href="{url}" target="_blank" rel="noopener noreferrer">{cta}</a><a class="button secondary" href="/contact.html">Request a Demo</a></div>')
        body+=f'''<section class="section split"><div><span class="eyebrow">Position in the ecosystem</span><h2>One connected offering, not a separate CRM platform.</h2><p>{desc}</p><p>This page describes the <strong>{kind.lower()}</strong> within the company-owned wCRM ecosystem.</p></div><div><h2>Plan the right setup</h2><ul class="checks"><li>Confirm the operational use case</li><li>Review required platform accounts and permissions</li><li>Map customer consent and data responsibilities</li><li>Agree onboarding or integration support</li></ul></div></section><section class="cta"><h2>See whether this fits your workflow.</h2><a class="button light" href="{url}" target="_blank" rel="noopener noreferrer">{cta}</a></section>'''
        write(f'products/{slug}.html',shell(f'products/{slug}.html',title,desc,body,title))
    overview=hero('Company-owned ecosystem','wCRM: core CRM, companion app and connected integrations.','These offerings belong to one SRLINES product ecosystem. Their roles are labelled so a core platform, mobile app, marketplace app, plugin and integration are not mistaken for separate CRMs.')+'<section class="section">'+cards(prod_cards)+'</section>'
    write('products/index.html',shell('products/index.html','Products & wCRM Ecosystem','Explore the company-owned wCRM core platform, mobile app, marketplace apps, plugin and integrations.',overview,'Products'))

    p_cards=[]
    for slug,title,tag,desc,cat in portfolio:
        p_cards.append((cat.title(),title,tag,f'<a href="/portfolio/{slug}.html">Read project profile →</a>'))
        body=hero('Client project · Developed for a client',title,tag,'<div class="actions"><a class="button" href="/contact.html">Discuss a similar project</a><a class="button secondary" href="/portfolio/index.html">All client projects</a></div>')
        body+=f'''<section class="section split"><div><h2>Project context</h2><p>{desc}</p></div><div><h2>Implementation perspective</h2><p>The repository identifies this project by name but does not provide enough evidence to publish a client identity, detailed feature inventory, results or public destination. Those details are deliberately not invented.</p></div></section>'''
        write(f'portfolio/{slug}.html',shell(f'portfolio/{slug}.html',title+' — Client Project',tag+' A client project developed by SRLINES.',body,title))
    overview=hero('Portfolio','Selected client projects, clearly separated from SRLINES products.','SignSyncer, FormSyncer and Whatsell were developed for clients. Their brands and businesses are not presented as owned by SRLINES.')+'''<section class="section"><div class="filters" aria-label="Filter client projects"><button class="active" data-filter="all">All</button><button data-filter="web">Web</button><button data-filter="automation">Automation</button><button data-filter="commerce">Commerce</button></div><div class="cards portfolio-grid">'''+''.join(f'<article data-category="{cat}"><span>Client project</span><h3>{title}</h3><p>{tag}</p><a href="/portfolio/{slug}.html">View client project →</a></article>' for slug,title,tag,desc,cat in portfolio)+'</div></section>'
    write('portfolio/index.html',shell('portfolio/index.html','Client Project Portfolio','Explore SignSyncer, FormSyncer and Whatsell as client projects developed by SRLINES—not company-owned products.',overview,'Portfolio'))

    industries=[('real-estate','Real Estate Solutions','Connect property enquiries, sales follow-up and campaign workflows.','Developers, agencies and property teams can combine responsive web experiences, advertising operations, workflow automation and wCRM conversation management.'),('ecommerce','Ecommerce Solutions','Connect storefront activity with customer communication.','Commerce teams can scope storefront development, transactional notifications, advertising and automation across Shopify, WooCommerce, wCRM and available APIs.'),('isp','ISP Solutions','Build clearer customer and operational workflows for ISPs.','Internet service providers can explore customer portals, enquiry management, payment-related integrations and automated service workflows, subject to available systems and permissions.')]
    for slug,title,tag,text in industries:
        body=hero('Industry solutions',title,tag,'<div class="actions"><a class="button" href="/contact.html">Request a Quote</a></div>')+f'''<section class="section split"><div><h2>Where we can help</h2><p>{text}</p></div><div><h2>Possible building blocks</h2><ul class="checks"><li>Website or application delivery</li><li>wCRM customer-conversation workflows</li><li>n8n integration and automation</li><li>Digital advertising and measurement support</li></ul></div></section><section class="cta"><h2>Map a solution around your systems.</h2><a class="button light" href="/contact.html">Discuss Your Project</a></section>'''
        write(f'industries/{slug}.html',shell(f'industries/{slug}.html',title,tag,body,title))

    contact=hero('Contact SRLINES','Tell us what needs to work better.','Request a quotation for a service, ask for a wCRM demo or outline an integration requirement.')+'''<section class="section contact-layout"><form id="contact-form" action="mailto:contact@srlines.net" method="post" enctype="text/plain" novalidate><h2>Request a quote</h2><p>This form submits to the existing wCRM form integration. If it is unavailable, your email application is the fallback; you can also use the direct actions alongside.</p><label>Name <input name="name" autocomplete="name" required></label><label>Business email <input type="email" name="email" autocomplete="email" required></label><label>Phone <input type="tel" name="phone" autocomplete="tel"></label><label>Area of interest <select name="interest" required><option value="">Choose one</option><option>Software development</option><option>wCRM</option><option>Automation / n8n</option><option>Digital advertising</option><option>NTN consultancy</option><option>Meta verification consultancy</option></select></label><label class="full">Project or requirement <textarea name="message" rows="6" required></textarea></label><label class="trap" aria-hidden="true">Website<input name="wcrm_website" tabindex="-1" autocomplete="off"></label><button class="button" type="submit">Send Request</button><div class="form-status" data-wcrm-result role="status" aria-live="polite"></div></form><aside><h2>Direct contact</h2><p><a href="mailto:contact@srlines.net">contact@srlines.net</a></p><p><a href="https://wa.me/923000941558" target="_blank" rel="noopener noreferrer">WhatsApp +92 300 0941558</a></p><p>Sadiqabad, Punjab, Pakistan</p><p class="notice">Do not send passwords or secret API keys through this form. Access requirements are agreed after scope and identity are confirmed.</p></aside></section><script src="https://crm.srlines.net/form-widget.js" data-form-id="wf_n7XM70piQmFNx5ZJY7kfckWj" data-form-selector="#contact-form" defer></script>'''
    write('contact.html',shell('contact.html','Contact / Request a Quote','Contact SRLINES for a software, service, automation or wCRM quotation.',contact,'Contact'))

    privacy=hero('Legal','Privacy Policy','How SRLINES handles information submitted through this website and related enquiries.')+'''<article class="legal"><h2>Information we receive</h2><p>We may receive identity, contact, business and project information you submit, plus ordinary technical request data produced when a website is accessed.</p><h2>Why it is used</h2><p>Information may be used to respond to enquiries, prepare quotations, provide requested services, protect systems and meet legal obligations.</p><h2>Forms and processors</h2><p>The quotation form uses the existing wCRM form integration hosted at crm.srlines.net. Its availability and submission confirmation determine whether a form request was received. You may instead email us.</p><h2>Sharing and retention</h2><p>Information is shared only where needed for service delivery, legal compliance or a processor acting on our behalf. Retention depends on the enquiry, contract and applicable requirements.</p><h2>Your choices</h2><p>Contact <a href="mailto:contact@srlines.net">contact@srlines.net</a> with a relevant privacy request. Rights and exceptions depend on applicable law.</p><p><strong>Last updated:</strong> 30 September 2026.</p></article>'''
    terms=hero('Legal','Terms of Service','General website and enquiry terms. A signed proposal or service agreement controls project-specific delivery.')+'''<article class="legal"><h2>Website information</h2><p>Website content is general information and may change. Marketplace, platform and government decisions remain controlled by their respective operators.</p><h2>Services and quotations</h2><p>Scope, fees, access, delivery responsibilities, intellectual property, support and acceptance criteria are established in the applicable quotation or agreement. No completion date or price is implied by this website.</p><h2>Consultancy limitations</h2><p>NTN and Meta verification services provide preparation and guidance. SRLINES is not a government authority and cannot guarantee registration, verification, approval or platform decisions.</p><h2>Third-party services</h2><p>External platforms have their own terms, charges and availability. Customers remain responsible for authorised access, lawful data use and compliance relevant to their operations.</p><h2>Contact</h2><p>Questions may be sent to <a href="mailto:contact@srlines.net">contact@srlines.net</a>.</p><p><strong>Last updated:</strong> 30 September 2026.</p></article>'''
    write('privacy.html',shell('privacy.html','Privacy Policy','SRLINES website privacy policy covering enquiries, forms, use, sharing and choices.',privacy,'Privacy'))
    write('terms.html',shell('terms.html','Terms of Service','General SRLINES website, quotation, consultancy and third-party service terms.',terms,'Terms'))

    notfound=hero('404','That page could not be found.','The address may have changed, or the page may no longer be public. Use the links below to continue.','<div class="actions"><a class="button" href="/">Go home</a><a class="button secondary" href="/contact.html">Contact SRLINES</a></div>')
    write('404.html',shell('404.html','Page Not Found','The requested SRLINES page could not be found.',notfound,'404'))

    paths=['']+[p for g in NAV.values() for _,p in g]+['/privacy.html','/terms.html']
    urls='\n'.join(f'  <url><loc>{DOMAIN}{p}</loc></url>' for p in paths)
    write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls+'\n</urlset>\n')
    write('robots.txt','User-agent: *\nAllow: /\nSitemap: https://srlines.net/sitemap.xml\n')

if __name__ == '__main__': build()
